version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  web:
    build: .
    container_name: url-shortener
    ports:
      - "5000:5000"
    depends_on:
      - redis

volumes:
  redis_data:
